# wrangler.toml
name = "inventory-cf"
compatibility_date = "2025-01-01"

[vars]
JWT_SECRET = "uJ8pL2NmQ9vX5zA7dE3rT1wY6gH0bN4o"

[[d1_databases]]
binding = "DB"
database_name = "inventory_db"
# ⚠️ 不要填 database_id（避免 UUID 校验问题）
